// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_formatif_final.DataAcess.Context;

#nullable disable

namespace Projet_formatif_final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_formatif_final.DataAcess.DTOs.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Nom");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Utilisateur regulier",
                            Nom = "Utilisateur"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gestionnaire",
                            Nom = "Gestionnaire"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Administrateur Systeme",
                            Nom = "Administrateur"
                        });
                });

            modelBuilder.Entity("Projet_formatif_final.DataAcess.DTOs.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("MotDePasse");

                    b.Property<string>("NomUtilisateur")
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("NomUtilisateur");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MotDePasse = "12345678",
                            NomUtilisateur = "TestUser1"
                        },
                        new
                        {
                            Id = 2,
                            MotDePasse = "87654321",
                            NomUtilisateur = "TestUser2"
                        });
                });

            modelBuilder.Entity("Projet_formatif_final.DataAcess.Pivots.RoleUtilisateurs", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UtilisateurId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("RoleUtilisateurs", (string)null);
                });

            modelBuilder.Entity("Projet_formatif_final.DataAcess.Pivots.RoleUtilisateurs", b =>
                {
                    b.HasOne("Projet_formatif_final.DataAcess.DTOs.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet_formatif_final.DataAcess.DTOs.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
